version: '3.8'

services:
  keycloak:
    image: quay.io/keycloak/keycloak:24.0.1
    command: start-dev
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_DB: postgres
      KC_DB_URL_HOST: postgres
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: keycloak
      KC_DB_DATABASE: keycloak
    ports:
      - "8080:8080"
    depends_on:
      - postgres

  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: keycloak
    volumes:
      - pgdata:/var/lib/postgresql/data

  nextjs-app:
    build:
      context: ./nextjs-app
      args:
        NEXT_PUBLIC_KEYCLOAK_URL: http://localhost:8080
        NEXT_PUBLIC_KEYCLOAK_REALM: myrealm
        NEXT_PUBLIC_KEYCLOAK_CLIENT_ID: nextjs-client
    environment:
      NEXT_PUBLIC_KEYCLOAK_URL: http://localhost:8080
      NEXT_PUBLIC_KEYCLOAK_REALM: myrealm
      NEXT_PUBLIC_KEYCLOAK_CLIENT_ID: nextjs-client
    ports:
      - "3000:3000"
    depends_on:
      - keycloak

volumes:
  pgdata: